apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: cm9vdA==
  mongo-root-password: cm9vdA==
  spring.data.mongodb.uri: bW9uZ29kYjovL3Jvb3Q6cm9vdEBtb25nb2RiLXNlcnZpY2U6MjcwMTcvYWRtaW4=


